### Create User
POST http://localhost:9009/api/v1/user
Content-Type: application/json

{
    "firstName": "Paul",
    "lastName": "George",
    "age": "35"
}

### Get all users
GET http://localhost:9009/api/v1/user


